apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaniko-demo-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: kaniko-demo
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kaniko-demo
    spec:
      containers:
      - name: kaniko-demo-container
        image: shekeriev/kaniko:latest
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: kaniko-demo-svc
  labels:
    app: kaniko-demo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: kaniko-demo
